version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

defaults: &defaults
  docker:
    - image: cimg/node:19.4.0
  working_directory: ~/app

jobs:
  install:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: "."
          paths:
            - "package.json"
            - "package-lock.json"
            - "project.json"
            - "jest.setup.js"
            - "jest.config.cjs"
            - "pitsby.config.cjs"
            - ".babelrc"
            - ".eslintrc"
            - ".firebaserc"
            - "firebase.json"
            - "node_modules"
            - ".git/*"
            - ".circleci/*"
            - "src/*"

  format:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Format
          command: npm run format

  docs:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Docs
          command: npm run docs
      - persist_to_workspace:
          root: "."
          paths:
            - "docs/*"

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Test
          command: npm run test -- --maxWorkers=2 --coverage --coverageReporters=lcov
      - coveralls/upload:
          verbose: true

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Deploy
          command: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  version: 2

  branch-workflow:
    jobs:
      - install
      - docs:
          requires:
            - install
      - format:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - docs
            - format
            - test
          filters:
            branches:
              only:
                - main
